/**
 * trackMelodyCore() is pitch.worker.ts's math extracted for the phone's
 * analysis bundle — extraction must not move a single sample. The golden file
 * was generated by running the PRE-refactor worker body (copied verbatim,
 * minus postMessage) over the deterministic signal below; exact equality here
 * is the proof that the refactor changed nothing and PITCH_DETECT_VERSION
 * rightly stayed at its value. If this test ever needs a tolerance, the math
 * changed and the version must bump instead.
 */
import { describe, expect, it } from 'vitest'
import { trackMelodyCore } from '../../src/renderer/src/audio/pitch-core'
import golden from './pitch-core-golden.json'

/** Deterministic synthetic vocal-ish signal, 48 kHz, ~4.5 s — must stay
 *  byte-identical to the generator that produced pitch-core-golden.json. */
function synth(): Float32Array {
  const sr = 48000
  const n = Math.floor(sr * 4.5)
  const x = new Float32Array(n)
  let seed = 0x5eed
  const rand = (): number => {
    // LCG — deterministic across engines (integer math + division)
    seed = (seed * 1664525 + 1013904223) >>> 0
    return seed / 0xffffffff - 0.5
  }
  let ph = 0 // integrated phase so vibrato stays a vibrato, not a chirp
  for (let i = 0; i < n; i++) {
    const t = i / sr
    let v = rand() * 0.0004 // floor noise
    if (t >= 0.8 && t < 2.2) {
      // steady A3 with light vibrato, loud
      const f = 220 * (1 + 0.004 * Math.sin(2 * Math.PI * 5.5 * t))
      ph += (2 * Math.PI * f) / sr
      v += 0.32 * Math.sin(ph) + 0.06 * Math.sin(2 * ph)
    } else if (t >= 2.2 && t < 2.9) {
      // octave leap up to A4
      ph += (2 * Math.PI * 440) / sr
      v += 0.3 * Math.sin(ph)
    } else if (t >= 3.1 && t < 3.35) {
      // short quiet far-off run (bleed-like): dropped by the cleaner
      ph += (2 * Math.PI * 1567.98) / sr
      v += 0.004 * Math.sin(ph)
    } else if (t >= 3.6 && t < 4.3) {
      // soft low D3 — above the gate, must survive
      ph += (2 * Math.PI * 146.83) / sr
      v += 0.05 * Math.sin(ph)
    }
    x[i] = v
  }
  return x
}

describe('trackMelodyCore — worker-extraction equality', () => {
  it('reproduces the pre-refactor worker output exactly', () => {
    const { f0, raw, rms, hopSec } = trackMelodyCore(synth(), golden.sampleRate)
    expect(hopSec).toBe(golden.hopSec)
    expect(f0.length).toBe(golden.f0.length)
    expect(Array.from(f0)).toEqual(golden.f0)
    expect(Array.from(raw)).toEqual(golden.raw)
    expect(Array.from(rms)).toEqual(golden.rms)
  })

  it('tracks the signal the way the fixture promises', () => {
    // Belt and braces: the fixture itself must describe a sane melody, so a
    // regenerated golden cannot silently bless nonsense.
    const at = (t: number): number => golden.f0[Math.round(t / golden.hopSec)]
    expect(at(1.5)).toBeGreaterThan(210)
    expect(at(1.5)).toBeLessThan(230) // A3
    expect(at(2.5)).toBeGreaterThan(430)
    expect(at(2.5)).toBeLessThan(450) // A4
    expect(at(3.2)).toBe(0) // quiet bleed-like run is gated
    expect(at(3.9)).toBeGreaterThan(140)
    expect(at(3.9)).toBeLessThan(154) // soft D3 survives
  })
})
